---
title: "R Notebook"
output: html_notebook
---

```{r}
install.packages("udpipe")
```

```{r}
library(udpipe)
library(tidyverse)
library(tidytext)
library(SnowballC)
```

```{r}
patents <- read_csv('../../data/data_subset1.csv')
```

```{r}
#patents <- patents %>% sample_n(1000, seed=42) 
patents %>% head()
```

```{r}
ipc_descriptions <- read_csv('../../data/CPC_descriptions.csv')
ipc_descriptions %>% head()
```

```{r}
ud_model <- udpipe_download_model(language = "english")
ud_model <- udpipe_load_model(ud_model$file_model)
```

```{r}
patents <- patents %>%
  unite(col="title_abstract", title, abstract, claims, sep=". ")
```

Una parola è importante se è caratterizzante per una ipc class

```{r}
paroleImportanti = c('to ask to the rest of the group')
```

```{r}

patents <- patents %>% mutate(code_1 = tolower(substr(ipc_classes, 0, 1)))
```

```{r}
tokens = patents %>%
          inner_join(ipc_descriptions 
                     %>% select(code_1, descr_1) %>% 
                distinct(),
                by="code_1") %>%
          select(code_1, descr_1, title_abstract) %>%
          unnest_tokens(word, title_abstract) %>%
          mutate(word = wordStem(word)) %>%
          count(code_1, descr_1, word, sort = TRUE)

head(tokens)
```

```{r}
tf_idf <- tokens %>%
  bind_tf_idf(word, code_1, n)
```

```{r}

for (code in unique(tokens$descr_1)){
  print(tf_idf %>%
 filter(descr_1 == code) %>%
 top_n(20, tf_idf) %>%
 ggplot(aes(x = reorder(word, tf_idf), y = tf_idf)) +
 geom_bar(stat = "identity") +
 coord_flip() +
 ggtitle(code) +
 xlab("") +
 theme_bw())
}
```
